
package JAXWS.topdown;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 *  WSDL File for FlightReservationServiceTopDown
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightReservationServiceTopDown", targetNamespace = "http://topdown.se/", wsdlLocation = "file:/C:/KTH/Course Materials/Semester 2/Web Services/Workspace/PWS-Homework2/src/main/java/topdown.wsdl")
public class FlightReservationServiceTopDown_Service
    extends Service
{

    private final static URL FLIGHTRESERVATIONSERVICETOPDOWN_WSDL_LOCATION;
    private final static WebServiceException FLIGHTRESERVATIONSERVICETOPDOWN_EXCEPTION;
    private final static QName FLIGHTRESERVATIONSERVICETOPDOWN_QNAME = new QName("http://topdown.se/", "FlightReservationServiceTopDown");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/KTH/Course Materials/Semester 2/Web Services/Workspace/PWS-Homework2/src/main/java/topdown.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTRESERVATIONSERVICETOPDOWN_WSDL_LOCATION = url;
        FLIGHTRESERVATIONSERVICETOPDOWN_EXCEPTION = e;
    }

    public FlightReservationServiceTopDown_Service() {
        super(__getWsdlLocation(), FLIGHTRESERVATIONSERVICETOPDOWN_QNAME);
    }

    public FlightReservationServiceTopDown_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTRESERVATIONSERVICETOPDOWN_QNAME, features);
    }

    public FlightReservationServiceTopDown_Service(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTRESERVATIONSERVICETOPDOWN_QNAME);
    }

    public FlightReservationServiceTopDown_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTRESERVATIONSERVICETOPDOWN_QNAME, features);
    }

    public FlightReservationServiceTopDown_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightReservationServiceTopDown_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightReservationServiceTopDown
     */
    @WebEndpoint(name = "FlightReservationServiceTopDownPort")
    public FlightReservationServiceTopDown getFlightReservationServiceTopDownPort() {
        return super.getPort(new QName("http://topdown.se/", "FlightReservationServiceTopDownPort"), FlightReservationServiceTopDown.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightReservationServiceTopDown
     */
    @WebEndpoint(name = "FlightReservationServiceTopDownPort")
    public FlightReservationServiceTopDown getFlightReservationServiceTopDownPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://topdown.se/", "FlightReservationServiceTopDownPort"), FlightReservationServiceTopDown.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTRESERVATIONSERVICETOPDOWN_EXCEPTION!= null) {
            throw FLIGHTRESERVATIONSERVICETOPDOWN_EXCEPTION;
        }
        return FLIGHTRESERVATIONSERVICETOPDOWN_WSDL_LOCATION;
    }

}
