
package JAXWS.topdown;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightReservationServiceTopDown", targetNamespace = "http://topdown.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightReservationServiceTopDown {


    /**
     * 
     * @param authToken
     * @param itineary
     * @param cardNumber
     * @return
     *     returns java.lang.String
     * @throws UnauthorizedException
     */
    @WebMethod(action = "bookTicket")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookTicket", targetNamespace = "http://topdown.se/", className = "JAXWS.topdown.BookTicket")
    @ResponseWrapper(localName = "bookTicketResponse", targetNamespace = "http://topdown.se/", className = "JAXWS.topdown.BookTicketResponse")
    public String bookTicket(
        @WebParam(name = "authToken", targetNamespace = "")
        String authToken,
        @WebParam(name = "itineary", targetNamespace = "")
        Itineary itineary,
        @WebParam(name = "cardNumber", targetNamespace = "")
        String cardNumber)
        throws UnauthorizedException
    ;

    /**
     * 
     * @param ticketNumber
     * @param authToken
     * @return
     *     returns JAXWS.topdown.Ticket
     * @throws UnauthorizedException
     */
    @WebMethod(action = "issueTicket")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "issueTicket", targetNamespace = "http://topdown.se/", className = "JAXWS.topdown.IssueTicket")
    @ResponseWrapper(localName = "issueTicketResponse", targetNamespace = "http://topdown.se/", className = "JAXWS.topdown.IssueTicketResponse")
    public Ticket issueTicket(
        @WebParam(name = "authToken", targetNamespace = "")
        String authToken,
        @WebParam(name = "ticketNumber", targetNamespace = "")
        String ticketNumber)
        throws UnauthorizedException
    ;

}
